name: TabCompleteFix
main: com.battleasya.TabCompleteFix
version: 1.0.1
author: Dennie
website: http://battleasya.com
depend: [PremiumVanish]
description: TabCompleteFix for iSpigot2.
commands:
  tcftoggle:
    description: Enable or disable the fix.
permissions:
  tcf.admin:
    description: Enable or disable the fix.
    default: op