name: TabCompleteFix
main: com.battleasya.TabCompleteFix
version: 1.0.0
author: Dennie
description: TabCompleteFix for iSpigot2
website: http://battleasya.com
depend: [PremiumVanish]
commands:
  tcftoggle:
    description: Toggle on or off
permissions:
  tcf.admin:
    description: Toggle on or off
    default: op