name: TabCompleteFix
main: com.battleasya.TabCompleteFix
version: 1.0.2
author: Dennie
website: http://battleasya.com
description: TabCompleteFix for iSpigot2.
depend: [PremiumVanish]
commands:
  tcftoggle:
    description: Enable or disable the fix.
permissions:
  tcf.admin:
    description: Enable or disable the fix.
    default: op