name: TabCompleteFix
main: com.battleasya.TabCompleteFix
depend: [PremiumVanish]
version: 1.0.0
authors: [Dennie]
description: TabCompleteFix for iSpigot2
website: http://battleasya.com
commands:
  tcftoggle:
    description: Toggle on or off TabCompleteFix
permissions:
  tcf.admin:
    description: Toggle on or off TabCompleteFix